CPUMIN=392000
CPUMAX=996000
GOVERNOR=interactive
SERIALCON=ttyS0
ARCH=arm64

UBOOT_TARGET_MAP=";spi;u-boot.bin"

CONSOLE_AUTOLOGIN=no
ROOTPWD=root
FORCE_BOOTSCRIPT_UPDATE=yes
VENDOR=Armbian
NETWORKING_STACK=network-manager
INCLUDE_HOME_DIR=yes

# Skip unneeded wifi drivers
declare -g KERNEL_DRIVERS_SKIP+=(driver_generic_bring_back_ipx driver_mt7921u_add_pids driver_rtl8152_rtl8153 driver_rtl8189ES
    driver_rtl8189FS driver_rtl8192EU driver_rtl8811_rtl8812_rtl8814_rtl8821 driver_xradio_xr819 driver_rtl8811CU_rtl8821C
    driver_rtl8188EU_rtl8188ETV driver_rtl88x2bu driver_rtw88 driver_rtl88x2cs driver_rtl8822cs_bt driver_rtl8723DS
    driver_rtl8822BS driver_uwe5622 driver_rtl8723cs driver_rtl8852bs driver_rtl8723DU)

if [[ $TFABOOT == yes ]]; then
	UBOOT_TARGET_MAP=";sd;sdcard-loader.bin"
else
	if [[ $SECUREBOOT == yes ]]; then
		UBOOT_TARGET_MAP=";spi;u-boot-dtb.bin spl/u-boot-spl.bin u-boot-with-spl-pbl.bin"
	fi
fi


KERNELDIR='linux-qoriq'
KERNELSOURCE='https://github.com/nxp-qoriq/linux.git'
KERNELBRANCH="branch:lf-6.6.y"
KERNEL_MAJOR_MINOR="6.6"

BOOTBRANCH='tag:v2024.10'

ATFSOURCE='https://github.com/nxp-qoriq/atf.git'
ATFDIR='arm-trusted-firmware-qoriq'
ATFBRANCH='branch:lf_v2.10'
ATF_TARGET_MAP="bl31;;build/fvp/release/bl31.bin"

RCWDIR='rcw-qoriq'

OPTEESOURCE='https://github.com/nxp-qoriq/optee_os.git'
OPTEEBRANCH='branch:lf-6.6.36_2.1.0'
OPTEEDIR='optee_os-qoriq'

PFESOURCE='https://github.com/nxp-qoriq/qoriq-engine-pfe-bin.git'
PFEBRANCH='branch:lf-6.6.36-2.1.0'
PFEDIR='pfe-engine'

FMUCODESOURCE='https://github.com/NXP/qoriq-fm-ucode'
FMUCODEBRANCH='branch:LSDK-21.08'
FMUCODEDIR='fm-ucode'

write_uboot_platform() {
	if [[ $BOARD == "trustbox-401" || $BOARD == "trustbox-201"  ]]; then
		dd if=$1/sdcard-loader.bin of=$2 bs=512 seek=8 status=noxfer > /dev/null 2>&1
	fi
}

uboot_custom_postprocess() {
	(fetch_from_repo "$RCWSOURCE" "$RCWDIR" "$RCWBRANCH" "yes")
	(fetch_from_repo "$OPTEESOURCE" "$OPTEEDIR" "$OPTEEBRANCH" "yes")
	(fetch_from_repo "$FMUCODESOURCE" "$FMUCODEDIR" "$FMUCODEBRANCH" "yes")

	local atfdir="$SRC/cache/sources/$ATFDIR/${ATFBRANCH##*:}"
	local ubootdir="$SRC/cache/sources/$BOOTSOURCEDIR"
	local rcwdir="$SRC/cache/sources/$RCWDIR/${RCWBRANCH##*:}"
	local teedir="$SRC/cache/sources/$OPTEEDIR/${OPTEEBRANCH##*:}"
	local fmucodedir="$SRC/cache/sources/$FMUCODEDIR/${FMUCODEBRANCH##*:}"

	pushd $rcwdir > /dev/null
	display_alert "Building RCW" "" "info"
	advanced_patch "rcw" "rcw-qoriq" "$BOARD"
	make
	popd > /dev/null

	pushd $teedir > /dev/null
	display_alert "Building OP-TEE" "" "info"
	make PLATFORM=${OPTEE_PLATFORM}
	popd > /dev/null

	pushd $atfdir > /dev/null
	make distclean
	display_alert "Building TF-A" "" "info"

	make CROSS_COMPILE="$CCACHE $toolchain/$ATF_COMPILER" PLAT=${ATF_PLATFORM} \
		all fip pbl BOOT_MODE=${ATF_BOOT_MODE} RCW="$rcwdir/${RCWPATH[${ATF_BOOT_MODE}$secext]}" SPD=opteed \
		BL32="$teedir/out/arm-plat-ls/core/tee-raw.bin" \
		BL33="$ubootdir/u-boot.bin" $secureopt $fuseopt

	if [[ ${ATF_BOOT_MODE} == sd ]]; then
		dd if=build/${ATF_PLATFORM}/release/bl2_sd$secext.pbl of="sdcard-loader.bin" bs=512
		dd if=build/${ATF_PLATFORM}/release/fip.bin of="sdcard-loader.bin" bs=512 seek=2040
		if [[ -n "${FMAN_UCODE}" ]]; then
			dd if=$fmucodedir/$FMAN_UCODE of="sdcard-loader.bin" bs=512 seek=18424
		fi
		cp sdcard-loader.bin $ubootdir/
	fi

	popd > /dev/null

	if [ $BOARD == "trustbox-101" ]; then
		(fetch_from_repo "$PFESOURCE" "$PFEDIR" "$PFEBRANCH" "yes")
	fi

	display_alert "Custom postprocess complete" "" "info"
}

family_tweaks() {

	if [ $BOARD == "trustbox-101" ]; then
		# copy ATF artifacts
		cp $SRC/cache/sources/$ATFDIR/${ATFBRANCH##*:}/build/${ATF_PLATFORM}/release/{bl2_${ATF_BOOT_MODE}$secext.pbl,fip.bin} ${SDCARD}/
		# copy PFE firmware
		cp $SRC/cache/sources/$PFEDIR/${PFEBRANCH##*:}/ls1012a/u-boot/pfe_fw_sbl.itb ${SDCARD}/
	fi
}
